title: Arthur Tainmont
description: Curriculum Vitae
url: "https://tainmontarthur.cv"
baseurl: ""  # Leave this blank if your site is served from the root
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
